/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface Message : NSObject <TBase, NSCoding> {
  NSString * __text;

  BOOL __text_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=text, setter=setText:) NSString * text;
#endif

- (id) init;
- (id) initWithText: (NSString *) text;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) text;
- (void) setText: (NSString *) text;
#endif
- (BOOL) textIsSet;

@end

@interface Chat : NSObject <TBase, NSCoding> {
  int32_t __revision;
  NSMutableArray * __messages;

  BOOL __revision_isset;
  BOOL __messages_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=revision, setter=setRevision:) int32_t revision;
@property (nonatomic, retain, getter=messages, setter=setMessages:) NSMutableArray * messages;
#endif

- (id) init;
- (id) initWithRevision: (int32_t) revision messages: (NSMutableArray *) messages;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) revision;
- (void) setRevision: (int32_t) revision;
#endif
- (BOOL) revisionIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) messages;
- (void) setMessages: (NSMutableArray *) messages;
#endif
- (BOOL) messagesIsSet;

@end

@protocol ChatAppAPI <NSObject>
- (int32_t) addMessage: (Message *) message;  // throws TException
- (int32_t) getChatRevision;  // throws TException
- (Chat *) getChat;  // throws TException
@end

@interface ChatAppAPIClient : NSObject <ChatAppAPI> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ChatAppAPIProcessor : NSObject <TProcessor> {
  id <ChatAppAPI> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithChatAppAPI: (id <ChatAppAPI>) service;
- (id<ChatAppAPI>) service;
@end

@interface ChatAppAPIConstants : NSObject {
}
@end
