/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface ListItem : NSObject <TBase, NSCoding> {
  NSString * __text;

  BOOL __text_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=text, setter=setText:) NSString * text;
#endif

- (id) init;
- (id) initWithText: (NSString *) text;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) text;
- (void) setText: (NSString *) text;
#endif
- (BOOL) textIsSet;

@end

@protocol ListApp <NSObject>
- (BOOL) addListItem: (ListItem *) listItem;  // throws TException
@end

@interface ListAppClient : NSObject <ListApp> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ListAppProcessor : NSObject <TProcessor> {
  id <ListApp> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithListApp: (id <ListApp>) service;
- (id<ListApp>) service;
@end

@interface ListAppConstants : NSObject {
}
@end
